name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd backend
          python -m pytest tests/

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          
      - name: Run tests
        run: |
          cd frontend
          npm test

  docker-build:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test backend container
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }} ./backend
          docker run --name test-backend -d ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }}
          sleep 5
          docker ps
          docker logs test-backend
          docker stop test-backend

      - name: Build and test frontend container
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }} ./frontend
          docker run --name test-frontend -d ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }}
          sleep 5
          docker ps
          docker logs test-frontend
          docker stop test-frontend

      - name: Push backend image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/devops-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-backend:latest

      - name: Push frontend image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/devops-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-frontend:latest

  test-docker-compose:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Start containers with docker-compose
        run: |
          docker-compose up -d

      - name: Check running containers
        run: docker-compose ps

      - name: Test backend health
        run: |
          sleep 10
          curl http://localhost:8000/health

      - name: Test frontend availability
        run: |
          curl -I http://localhost

      - name: Show logs
        if: always()
        run: docker-compose logs

      - name: Stop containers
        if: always()
        run: docker-compose down
